// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rjgzqagobndphpvhuquq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJqZ3pxYWdvYm5kcGhwdmh1cXVxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkyOTcwNTAsImV4cCI6MjA2NDg3MzA1MH0.mKqJPhnXA7mPTW4SziW5IqaPHTXUbbqO5YY2Twp-6iQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);